<p><a href="chrome://dino/">chrome://dino/</a></p>
<div class="code_element"><div class="lang_line"><text>javascript</text><button class="copy_code_button" onclick="CopyCode(this)"><svg style="width: 1.2em;height: 1.2em;" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 4h3a1 1 0 0 1 1 1v15a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h3m0 3h6m-5-4v4h4V3h-4Z"/></svg><text class="unselectable">Copy code</text></button></div><div class="code language-javascript"><div class="highlight"><pre><span></span><span class="nx">Runner</span><span class="p">.</span><span class="nx">instance_</span><span class="p">.</span><span class="nx">setSpeed</span><span class="p">(</span><span class="mf">1000</span><span class="p">)</span>
</pre></div></div></div>
<div class="code_element"><div class="lang_line"><text>javascript</text><button class="copy_code_button" onclick="CopyCode(this)"><svg style="width: 1.2em;height: 1.2em;" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 4h3a1 1 0 0 1 1 1v15a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h3m0 3h6m-5-4v4h4V3h-4Z"/></svg><text class="unselectable">Copy code</text></button></div><div class="code language-javascript"><div class="highlight"><pre><span></span><span class="nx">Runner</span><span class="p">.</span><span class="nx">prototype</span><span class="p">.</span><span class="nx">gameOver</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="kd">function</span><span class="p">(){}</span>
</pre></div></div></div>

<p>Setting the current score
Let’s set the score to 12345. You can set any other score less than 99999. The current score is reset on game over.</p>
<div class="code_element"><div class="lang_line"><text>javascript</text><button class="copy_code_button" onclick="CopyCode(this)"><svg style="width: 1.2em;height: 1.2em;" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 4h3a1 1 0 0 1 1 1v15a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h3m0 3h6m-5-4v4h4V3h-4Z"/></svg><text class="unselectable">Copy code</text></button></div><div class="code language-javascript"><div class="highlight"><pre><span></span><span class="nx">Runner</span><span class="p">.</span><span class="nx">instance_</span><span class="p">.</span><span class="nx">distanceRan</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="mf">12345</span><span class="w"> </span><span class="o">/</span><span class="w"> </span><span class="nx">Runner</span><span class="p">.</span><span class="nx">instance_</span><span class="p">.</span><span class="nx">distanceMeter</span><span class="p">.</span><span class="nx">config</span><span class="p">.</span><span class="nx">COEFFICIENT</span>
</pre></div></div></div>

<p>You can control how high the dino jumps by using the below function. Adjust the value as necessary.</p>
<div class="code_element"><div class="lang_line"><text>javascript</text><button class="copy_code_button" onclick="CopyCode(this)"><svg style="width: 1.2em;height: 1.2em;" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 4h3a1 1 0 0 1 1 1v15a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h3m0 3h6m-5-4v4h4V3h-4Z"/></svg><text class="unselectable">Copy code</text></button></div><div class="code language-javascript"><div class="highlight"><pre><span></span><span class="nx">Runner</span><span class="p">.</span><span class="nx">instance_</span><span class="p">.</span><span class="nx">tRex</span><span class="p">.</span><span class="nx">setJumpVelocity</span><span class="p">(</span><span class="mf">10</span><span class="p">)</span>
</pre></div></div></div>

<div class="code_element"><div class="lang_line"><text>javascript</text><button class="copy_code_button" onclick="CopyCode(this)"><svg style="width: 1.2em;height: 1.2em;" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 4h3a1 1 0 0 1 1 1v15a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h3m0 3h6m-5-4v4h4V3h-4Z"/></svg><text class="unselectable">Copy code</text></button></div><div class="code language-javascript"><div class="highlight"><pre><span></span><span class="nx">Runner</span><span class="p">.</span><span class="nx">prototype</span><span class="p">.</span><span class="nx">gameOver</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="kd">function</span><span class="p">(){}</span>
<span class="nx">Runner</span><span class="p">.</span><span class="nx">instance_</span><span class="p">.</span><span class="nx">setSpeed</span><span class="p">(</span><span class="mf">1000</span><span class="p">)</span>
</pre></div></div></div>